sudo: false
os:
  - linux

env:
  - CONDA_PY=3.8
  - CONDA_PY=3.7

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

install:
  - conda create --yes -n env_name python=$CONDA_PY
  - conda install --yes -n env_name --file ci/conda_requirements.txt
  - source activate env_name
  - pip install -r ci/pip_requirements.txt
  - make install

script:
  - make lint
  - make test-cov
  - make test-install

after_success:
  - coveralls
